core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("processor.urls")),
    re_path(r"^celery-progress/", include("celery_progress.urls"))
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

processor/urls.py
from django.urls import path
from .import views

app_name = "processor"

urlpatterns = [
    path("", views.ConvertionOptions.as_view(), name="convertion_options"),
    path("convert-to-selectable-pdf", 
        views.StaticPDFToSelectablePDFView.as_view(), 
        name="convert_to_selectable_pdf"),
    
    path("remove-watermark-from-pdf", 
        views.RemoveWatermarkFromPDFView.as_view(), 
        name="remove_watermark_from_pdf"),

    path("convert-pdfs-pngs", 
        views.ConvertPDFToPNGsView.as_view(), 
        name="convert_pdf_to_pngs"),

    path("merge-pdfs", 
        views.MergePDFFilesView.as_view(), 
        name="merg_pdfs"),

    path("extract-text-from-pdf", 
        views.ExtractTextFromPDFView.as_view(), 
        name="extract_text_from_pdf"),

    # path("convert-to-png", views.convert_to_png, name="convert_to_png"),
    # path("convert-images-to-png", views.images_to_pdf, name="images_to_pdf"),
    # path("merge-pdfs", views.MergePDFsView.as_view(), name="merge_pdfs"),


    # path("order/<str:task_id>", views.processing_view, name="processing"),
    # path('stream/<str:task_id>', views.stream_task_progress, name='stream_task_progress')
]

webapp/urls.py
from django.urls import path
from .import views

app_name = "webapp"

urlpatterns = [
    path("", views.convertion_options, name="convertion_options"),
    path("convert-to-pdf", views.convert_to_pdf, name="convert_to_pdf"),
    path("convert-to-png", views.convert_to_png, name="convert_to_png"),
    path("convert-images-to-png", views.images_to_pdf, name="images_to_pdf"),
    path("merge-pdfs", views.MergePDFsView.as_view(), name="merge_pdfs"),


    path("order/<str:task_id>", views.processing_view, name="processing"),
    path('stream/<str:task_id>', views.stream_task_progress, name='stream_task_progress')
]

webapp/models.py
from django.db import models
from django.utils import timezone

class PDFOperationOrder(models.Model):
    file = models.FileField(upload_to="uploads/documents")
    remove_bg = models.BooleanField(default=False)
    pub_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return str(self.pub_date)

class ImageOperationOrder(models.Model):
    images = models.ManyToManyField("Image")
    remove_bg = models.BooleanField(default=False)
    merge = models.BooleanField(default=True)
    pub_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return str(self.pub_date)
    
class Image(models.Model):
    file = models.FileField(upload_to="uploads/images")


class UploadedFile(models.Model):
    type = models.CharField(max_length=10, blank=True)
    file = models.FileField(upload_to="uploads/files")

class MultipleFile(models.Model):
    files = models.ManyToManyField("UploadedFile")
    pub_date = models.DateTimeField(default=timezone.now)

webapp/forms.py
from . models import PDFOperationOrder, ImageOperationOrder
from django import forms
from django.contrib.auth.models import User

class PDFOperationOrderForm(forms.ModelForm):
    class Meta:
        model = PDFOperationOrder
        fields = ['file', 'remove_bg']

class ImageOperationOrderForm(forms.ModelForm):
    class Meta:
        model = ImageOperationOrder
        fields = ['images', 'remove_bg']

webapp/views.py
import datetime
import time
from django.shortcuts import render, redirect
from . forms import PDFOperationOrderForm, ImageOperationOrderForm
from . models import Image, ImageOperationOrder, UploadedFile, MultipleFile
from . tasks import static_pdf_to_selectable_pdf, pdf_to_pngs, images_to_pdf_task, task_merge_pdfs
from django.core.files.storage import FileSystemStorage
from core.celery import get_celery_worker_status
from celery.result import AsyncResult
from django.http import StreamingHttpResponse
from django.views import View


def convertion_options(request):
    template_name = "webapp/convertion_options.html"
    return render(request, template_name)

class ValidateFileMixin(View):
    """ This class validates the files uploaded by the user against defined
        acceptable extensions.
    """
    def validate_files(self, files, acceptable_extensions) -> bool:
        for file in files:
            file_extension = file.name.split(".")[-1]
            if not file_extension in acceptable_extensions:
                return False
            return True
 
def convert_to_png(request):
    template_name = "webapp/convert_to_png.html"
    form = PDFOperationOrderForm()

    if request.method == "POST":
        form = PDFOperationOrderForm(request.POST, request.FILES)
        if form.is_valid():
            order = form.save()
            input_file = order.file.name
            fn = "".join(input_file.split("/")[-1].split(".")[:1])
            request.session["pngs_url"] = "http://127.0.0.1:8000/resources/processed/"+fn+".zip"
            
            # initiate pdf processing tast
            task = pdf_to_pngs.delay(order.id)
            return redirect("webapp:processing", task.task_id)

    context = {
        "form":form,
    }
    return render(request, template_name, context)


def images_to_pdf(request):
    template_name = "webapp/images_to_pdf.html"
    acceptable_extensions = ["png", "jpg"]

    if request.method == "POST":
        files = request.FILES.getlist("images")
        remove_bg = False if request.POST.get("remove_bg") == None else True

        # Validating images
        for file in files:
            file_extension = file.name.split(".")[-1]
            if not file_extension in acceptable_extensions:
                request.session["error_message"] = "Only .png and .jpg files are acceptable"
                return redirect("webapp:images_to_pdf")

        # saving images
        images = []
        for file in files:
            images.append(Image.objects.create(file=file))
        
        order = ImageOperationOrder.objects.create(remove_bg=remove_bg)
        order.images.add(*images)

        request.session["pdf_url"] = "http://127.0.0.1:8000/resources/processed/"+"images_to_pdf"+str(order.pk)+".pdf"
        
        # initiate pdf processing tast
        task = images_to_pdf_task.delay(order.id)
        return redirect("webapp:processing", task.task_id)
    return render(request, template_name)


def convert_to_pdf(request):
    template_name = "webapp/convert_to_pdf.html"
    form = PDFOperationOrderForm()

    if request.method == "POST":
        form = PDFOperationOrderForm(request.POST, request.FILES)
        if form.is_valid():
            order = form.save()
            input_file = order.file.name
            fn = input_file.split("/")[-1]
            request.session["pdf_url"] = "http://127.0.0.1:8000/resources/processed/"+fn
            
            # initiate pdf processing tast
            task = static_pdf_to_selectable_pdf.delay(order.id)
            return redirect("webapp:processing", task.task_id)

    context = {
        "form":form,
    }
    return render(request, template_name, context)


def processing_view(request, task_id):
    template_name = "webapp/processing.html"
    
    pdf_url = request.session.pop("pdf_url", "")
    pngs_url = request.session.pop("pngs_url", "")
    context = {
        "pdf_url" : pdf_url,
        "pngs_url" : pngs_url,
        "task_id":task_id,
    }
    return render(request, template_name, context)

def stream_task_progress(request, task_id):
    result = AsyncResult(task_id)
    def get_task_progress():
        i = 1
        while True:
            data = str(result.status) + "," + str(result.info)
            time.sleep(0.05)
            i +=1
            if result.status == "SUCCESS":
                yield 'data: SUCCESS\n\n'
                break

            yield 'data: %s\n\n' % data
    return StreamingHttpResponse(get_task_progress(), content_type='text/event-stream')


class MergePDFsView(ValidateFileMixin):
    template_name = "webapp/merge_pdfs.html"
    form_class  = PDFOperationOrderForm
    acceptable_extensions = ["pdf"]
    
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

    def post(self, request):
        files  = request.FILES.getlist("pdfs")
        if files is None:
            return rediret("webapp:merge_pdfs")

        if not self.validate_files(files, self.acceptable_extensions):
            request.session["error_message"] = "Only .pdf files are acceptable"        
            return redirect("webapp:merge_pdfs")

        # saving pdfs
        pdfs = []
        for file in files:
            pdfs.append(UploadedFile.objects.create(type="pdf", file=file))
        order = MultipleFile.objects.create()
        order.files.add(*pdfs)
        task_merge_pdfs(order.id)

        return redirect("webapp:merge_pdfs")

webapp/templates/webapp/convert_to_pdf.html
{% extends 'webapp/base_template.html' %}

{% block body %}
    {% if url %}
    <h1><a href="{{url}}" target="_blank">wait and download</a></h1>
    {% endif %}
    
    <form action="" method="POST" enctype="multipart/form-data">
        <h1>Convert to selectable pdf</h1>
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit">Submit</button>
    </form>
{% endblock body %}

webapp/templates/webapp/convert_to_png.html
{% extends 'webapp/base_template.html' %}

{% block body %}
    {% if url %}
    <h1><a href="{{url}}" target="_blank">wait and download</a></h1>
    {% endif %}
    
    <form action="" method="POST" enctype="multipart/form-data">
        <h1>Convert to pngs</h1>
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit">Submit</button>
    </form>
{% endblock body %}

webapp/templates/webapp/convertion_options.html
{% extends 'webapp/base_template.html' %}

{% block body %}
    <h1>Select option</h1>
    <div>
        <a href="{% url 'processor:convert_to_selectable_pdf' %}">Convert PDF to Selectable PDF</a>
    </div>

    <div>
        <a >Convert PDF to PNGs</a>
    </div>

    <div>
        <a >Convert Images to PDF</a>
    </div>

    <div>
        <a >Merge PDFs</a>
    </div>

    <div>
        <a href="">Extract text from images/pdfs</a>
    </div>

    <div>
        <a href="">Docx to pdf</a>
    </div>

{% endblock body %}

webapp/templates/webapp/images_to_pdf.html
{% extends 'webapp/base_template.html' %}

{% block body %}   
    <form action="" method="POST" enctype="multipart/form-data">
        <h1>Convert images to pdf</h1>
        {% csrf_token %}
        
        <input type="file" name="images" id="images" multiple accept=".jpg, .png">

        <div class="form-group">
            <label for="remove_bg">Remove Background</label>
            <input type="checkbox" name="remove_bg" id="">
        </div>

        <div class="form-group">
            <label for="merge">Merge</label>
            <input type="checkbox" name="merge" id="" checked>
        </div>

        <button type="submit">Submit</button>
    </form>
{% endblock body %}

webapp/templates/webapp/merge_pdfs.html
{% extends 'webapp/base_template.html' %}

{% block body %}   
    <form action="" method="POST" enctype="multipart/form-data">
        <h1>Merge PDFs</h1>
        {% csrf_token %}
        
        <input type="file" name="pdfs" id="pdfs" multiple accept=".pdf">

        <button type="submit">Submit</button>
    </form>
{% endblock body %}

webapp/templates/webapp/processing.html
{% extends 'webapp/base_template.html' %}

{% block body %}
    {% if pdf_url %}
    <h1><a href="{{pdf_url}}" target="_blank" class="hide" id="download-div">download</a></h1>
    {% endif %}

    {% if pngs_url %}
    <h1><a href="{{pngs_url}}" target="_blank" class="hide" id="download-div">download</a></h1>
    {% endif %}

    <div id="result"></div>

    <br>

    <script>
    if(typeof(EventSource) !== "undefined") {
        var source = new EventSource("/stream/{{task_id}}");
        source.onmessage = function(event) {
            document.getElementById("result").innerHTML = event.data + "<br>";
            
            if(event.data.includes("SUCCESS")){
                source.close();
                document.querySelector("#download-div").classList.remove("hide")
            }
        };
    } else {
        document.getElementById("result").innerHTML = "Sorry, your browser does not support server-sent events...";
    }
    </script>
    
{% endblock body %}